# use base python image with python latest
FROM python:3.6

WORKDIR /app/
# add requirements.txt to the image
ADD ./app.py /app/
RUN apt-get update
RUN apt-get -y install libpq-dev python-dev
ADD requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
CMD ["cd"]
CMD ["sh"] ["wait_for_rabbit_server.sh"]
CMD ["python", "new_racer.py"]
