version: '2'

services:
  # Start RabbitMQ Service
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.1-management
    environment:
      - SERVICE_NAME=rabbit
    ports:
    # forward port for debugging
      - "5672:5672"
      - "15672:15672"

  # Master
  master:
    build:
      context: .
      dockerfile: dockerfile_master
    hostname: master
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "5678:5678"  # for getting logs on websocket
    # setting up links for service discovery
    links:
      - rabbit


  ## currently harcoding racer, modify it to scale the racer as
  ## required and passing {variable} as name

  # First Racer
  racer1:
    build:
      context: .
      dockerfile: dockerfile_racer
    hostname: racer
    volumes:
      - .:/app
#
    #ports:
    # setting up links for service discovery
    command: python new_racer.py 1
    links:
      - rabbit
      - master

  # Second Racer
  racer2:
    build:
      context: .
      dockerfile: dockerfile_racer
    hostname: racer
    volumes:
      - .:/app
#
    #ports:
    # setting up links for service discovery
    command: python new_racer.py 2
    links:
      - rabbit
      - master

  # Third Racer
  racer3:
    build:
      context: .
      dockerfile: dockerfile_racer
    hostname: racer
    volumes:
      - .:/app
#
    #ports:
    # setting up links for service discovery
    command: python new_racer.py 3
    links:
      - rabbit
      - master